apiVersion: v1
kind: Service
metadata:
  name: nodedemo
  labels:
    app: nodedemo
spec:
  selector:
    app: nodedemo
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30061
  type: LoadBalancer